### ISSUE TITLE
Linuxbrew installation of Anvio (issues with Pip)

### ISSUE THREAD

**Issue by PlantDr430** [merenlab/homebrew-anvio#1]
Hello,
Below is the error message I am getting after running the installing with linuxbrew. I tested "brew doctor" prior to installation and everything was ready to go. I then used the commands "brew tap meren/anvio" and then "brew install anvio". Everything was going great until the end.

==> Installing merenlab/anvio/anvio
==> Downloading https://files.pythonhosted.org/packages/63/75/3a79f2474b59bd7edd4485afb102
Already downloaded: /home/swyka430/.cache/Homebrew/anvio-4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b1
Already downloaded: /home/swyka430/.cache/Homebrew/anvio--homebrew-virtualenv-16.0.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/anvio--homebrew-vi
==> python3 -s /tmp/anvio--homebrew-virtualenv-20180614-27256-zfmt3w/target/bin/virtualenv
==> Downloading https://files.pythonhosted.org/packages/bd/99/04dc59ced52a8261ee0f965a8968
Already downloaded: /home/swyka430/.cache/Homebrew/anvio--bottle-0.12.13.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/be/70/16cdd6c5ef799b2db2af4fd5f972
Already downloaded: /home/swyka430/.cache/Homebrew/anvio--pysam-0.11.1.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/21/17/3c49b7fafe10ed63bb7904ebf976
################################################################################### 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/f5/2c/5edf2488897cad4fb8c4ace86369
################################################################################### 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/21/eb/534ac46e63c51eabbfc768d8c11c
################################################################################### 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/b7/67/7e2a817f9e9c773ee3995c1e1520
################################################################################### 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
==> Downloading https://files.pythonhosted.org/packages/22/82/64dada5382a60471f85f16eb7d01
################################################################################### 100.0%
==> /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/pip install -v --no-deps --no-bi
Last 15 lines from /home/swyka430/.cache/Homebrew/Logs/anvio/09.pip:
  Removing source in /tmp/pip-req-build-kz6kcjud
Command "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-kz6kcjud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-z4oowrp2/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/include/site/python3.6/h5py" failed with error code 1 in /tmp/pip-req-build-kz6kcjud/
Exception information:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 779, in install
    spinner=spinner,
  File "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-kz6kcjud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-z4oowrp2/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/anvio/4/libexec/include/site/python3.6/h5py" failed with error code 1 in /tmp/pip-req-build-kz6kcjud/

I tried to run the test "anvi-self-test --suite mini" and I get a command not found error. 

swyka430@swyka430-HP-ENVY-x360-Convertible-15-bq1xx:/home$ anvi-self-test --suite mini
anvi-self-test: command not found

I am using a fresh install of Ubuntu 18.04 

Here are the 09.pip log file 

[09.pip.cc.txt](https://github.com/merenlab/homebrew-anvio/files/2104745/09.pip.cc.txt)
[09.pip.txt](https://github.com/merenlab/homebrew-anvio/files/2104746/09.pip.txt)

**Comment by ozcan** [comment]
Hi @PlantDr430,

I will look into this, but some dependencies like `numpy`, `scipy` or in this case `h5py` are very problematic to install with linuxbrew on some computers I had tested so far. I think you may get better results if you follow our Ubuntu installation [recipe](https://gist.github.com/meren/f1e674f774a30a209d82). 

Best,

**Comment by PlantDr430** [comment]
Thanks,
I tried the Ubuntu install as well and i had problems with that so that is why I switched to linuxbrew. I can try the Ubuntu installation again and report back issues if I have them.

**Comment by meren** [comment]
Hi @PlantDr430,

I am not surprised the Ubuntu recipe hasn't worked for you. We haven't really been keeping it up-to-date :/

But our Docker file is quite up-to-date, and there is enough information in it to make someone be able to use relevant packages to install:

https://gist.github.com/meren/65b1f1bfea1b53e87e10f025d1e4c29a


Best,

**Comment by PlantDr430** [comment]
Alright, I will take a look. One of the problems with the Ubuntu recipe is that it can't find the matching distribution for django==2.0.2  

There was another problem later on, as I tried installed django==1.11.13 as that was the latest one it could find, but I forget off the top of my head what the issue was.

Here is the django error:
Collecting django==2.0.2
  Could not find a version that satisfies the requirement django==2.0.2 (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13)
No matching distribution found for django==2.0.2

**Comment by ozcan** [comment]
Hey @PlantDr430,

Oh it makes sense, It seems python 2 is the default python version for your system. If you create  python3 virtualenv you should be able to follow same steps without any problems.

To create virtualenv:
```
sudo apt-get install python-virtualenv
virtualenv -p python3 ~/anvio-master
```

To activate virtualenv:
```
source ~/anvio-master/bin/activate
```
Then you should see `(anvio-master)` next to your command prompt like below:
![screen shot 2018-06-15 at 10 38 57 am](https://user-images.githubusercontent.com/940884/41476889-6f3278f8-7088-11e8-988f-6d1c437b997e.png)

Then you should be able to install those packages and anvio.
Best,

**Comment by PlantDr430** [comment]
I created and activated virtualenv and tried to reinstall anvio via homebrew and the Ubuntu recipe and I still get the same errors as before.


![screenshot from 2018-06-15 11-45-48](https://user-images.githubusercontent.com/29610303/41482226-29c490a8-7092-11e8-9af7-07bc2ec13f60.png)

I'm going to give the Docker install a try.

**Comment by PlantDr430** [comment]
I got it to install and ran the self-test with Docker. Thanks for the help!
